language: node_js

node_js:
  - "8"

cache:
  directories:
  - node_modules

before_script:
  - touch .env

script:
  - npm run build

deploy:
  provider: heroku
  email: "dev@cipherz.com"
  api_key:
    secure: $HEROKU_API_KEY
  app: "school-lottery"
  skip_cleanup: true
  on:
    branch: master